language: java
jdk:
  - openjdk14
addons:
  sonarcloud:
    organization: lexie93
    token: $SONAR_TOKEN
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=Lexie93_syncope -Dsonar.java.binaries=. -Dmaven.javadoc.skip=true

